import { FieldDefinition } from '../modules/content/content.types.js';
import { CollectionResponse } from '../modules/content/collection.schemas.js';

function tsTypeForField(field: FieldDefinition): string {
  switch (field.type) {
    case 'string':
    case 'text':
    case 'rich-text':
    case 'slug':
    case 'media':
    case 'date':
    case 'reference':
      return 'string';
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'select':
      if (field.options && field.options.length > 0) {
        return field.options.map((o) => JSON.stringify(o)).join(' | ');
      }
      return 'string';
    case 'multi-select': {
      const inner = field.options && field.options.length > 0
        ? field.options.map((o) => JSON.stringify(o)).join(' | ')
        : 'string';
      return `(${inner})[]`;
    }
    case 'multi-reference':
      return 'string[]';
    case 'repeater': {
      if (!field.subFields || field.subFields.length === 0) return 'Record<string, unknown>[]';
      const inner = field.subFields
        .map((s) => `  ${s.name}${s.required ? '' : '?'}: ${tsTypeForField(s)};`)
        .join('\n    ');
      return `Array<{\n    ${inner}\n  }>`;
    }
    default: {
      const _exhaustive: never = field.type;
      return 'unknown';
    }
  }
}

function interfaceName(slug: string): string {
  return slug
    .split('-')
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join('')
    + 'Entry';
}

export function generateTypes(collections: CollectionResponse[]): string {
  const lines: string[] = [];
  lines.push('// AUTO-GENERATED by `slatestack gen`. Do not edit by hand.');
  lines.push('// Run `slatestack gen` after changing collection schemas.');
  lines.push('');

  for (const coll of collections) {
    const name = interfaceName(coll.slug);
    lines.push(`export interface ${name} {`);
    lines.push(`  id: string;`);
    lines.push(`  slug: string;`);
    lines.push(`  status: "draft" | "published";`);
    lines.push(`  data: {`);
    for (const f of coll.fields as FieldDefinition[]) {
      const type = tsTypeForField(f);
      lines.push(`    ${f.name}${f.required ? '' : '?'}: ${type};`);
    }
    lines.push(`  };`);
    lines.push(`  createdAt: string;`);
    lines.push(`  updatedAt: string;`);
    lines.push(`}`);
    lines.push('');
  }

  lines.push('export type CollectionMap = {');
  for (const coll of collections) {
    lines.push(`  "${coll.slug}": ${interfaceName(coll.slug)};`);
  }
  lines.push('};');
  lines.push('');

  return lines.join('\n');
}
